- name: task & play level variables
  hosts: local
  connection: local
  vars_files:
  - vars.yaml
  tasks:
  - name: play level Variables
    ansible.builtin.debug:
      msg: " Course name is {{ course }} , Trainer is {{ trainer }} and duration is {{ duration }}"
  - name: task level variables
    vars:
      trainer: revanth
      duration: 60HRS
    ansible.builtin.debug:
      msg: " Course name is {{ course }} , Trainer is {{ trainer }} and duration is {{ duration }}"
    # vars_files is only valid at the play level, not inside a task.
  - name: variables  from different yaml
    ansible.builtin.debug:
      msg: " Course name is {{ course }} , Trainer is {{ trainer }} and duration is {{ duration }}"