- name: task & play level variables
  hosts: local
  connection: local
  vars_files:
  - vars.yaml
  tasks:
  - name: play level Variables
    ansible.builtin.debug:
      msg: " Course name is {{ course }} , Trainer is {{ trainer }} and duration is {{ duration }}"
  - name: task level variables
    vars:
      trainer: revanth
      duration: 60HRS
    ansible.builtin.debug:
      msg: " Course name is {{ course }} , Trainer is {{ trainer }} and duration is {{ duration }}"