- name: Variables playbook
  hosts: local
  connection: local
  variables: #play level variables
    COURSE: "DevOps with AWS"
    DURATION: 120HRS
    TRAINER: SivaKumarReddy
  tasks:
  - name: printing the varibles
    ansible.builtin.debug:
      msg: " course is {{COURSE}}, duration is {{DURATION}}, Trainer is {{TRAINER}}"