- name: Installing packages
  hosts: web
  become: yes
  tasks:
  - name: Install if RHEL
    ansible.builtin.dnf:
      name: mysql
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install if ubuntu
    ansible.builtin.apt:
      name: mysql
      state: present
    when: ansible_os_family == "Debian"
