- name: loops playbook
  hosts: local
  connection: local
  tasks:
  - name: print names using loops
    ansible.builtin.debug:
      msg: "Hello from {{ item }}"
    loop:
    - ramesh
    - suresh
    - sai
    - pavan
    - kousi