- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: " hello from {{ ramesh | default ('sivasai') }}, sivasai is a default value"

  - name: convert string to list
    vars:
      name: "aa, bb, cc, dd, ee"
    ansible.builtin.debug:
      msg: " converting string to list {{ name | split (',') }}"

  - name: converting map to list
    vars:
      course:
        name: ansible
        duration: 10hrs
        trainer: siva
    ansible.builtin.debug:
      msg: " conveting map to list {{ course | dict2items }}"

  - name: convert list to map
    vars:
      course:
        - {'key': 'name', 'value': 'ansible'}
        - {'key': 'duration', 'value': '10hrs'}
        - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: " conveting list  to map {{ course | items2dict }}"

  - name: upper to lower case
    vars:
      name: "SIVA sai Kumar"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"

  - name: lower to upper case
    vars:
      name: "SIVA sai Kumar"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: print max and min
    vars:
      list: [1,3,5,7,9,11,26]
    ansible.builtin.debug:
      msg: " Max is {{ list | max }}, min is {{ list|min }}"