- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: " hello from {{ ramesh | default ('sivasai') }}, sivasai is a default value"

  - name: convert string to list
    vars:
      name: "aa, bb, cc, dd, ee"
    ansible.builtin.debug:
      msg: " converting string to list {{ name | split (',') }}"

  - name: converting map to list
    vars:
      course:
        name: ansible
        duration: 10hrs
        trainer: siva
    ansible.builtin.debug:
      msg: " conveting map to list {{ course | dict2items }}"