- name: Installing the python modules
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
  - PyMySQL
  - cryptography
- name: Installing the mysql server
  ansible.builtin.package:
    name: mysql-server
    state: present
- name: start and enable mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: checking the root password is set or not
  community.mysql.mysql_info:
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}""
    login_host: "{{ mysql_host }}"
  register: mysql_info
  ignore_errors: true

- name: print the output
  ansible.builtin.debug:
    msg: " {{ mysql_info }}"

- name: setting up root password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass ExpenseApp@1"
  when: mysql_info.failed == true