- name: Removing the existing directory
  ansible.builtin.file:
    path: "{{ loaction }}"
    state: absent

- name: Creating a direcrtory
  ansible.builtin.file:
    path: "{{ loaction }}"
    state: directory

- name: downloading the code and unzipping
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
    dest: "{{ loaction }}"
    remote_src: yes
