- name: variables from files
  hosts: local
  connection: local
  tasks:
  - name: printing the vars from file
    ansible.builtin.debug:
     msg: " Course is {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"

  - name: printing the Task level varibles
    vars: # task level variables, accessible only within the task, it can override the play level variables also, local variable
      COURSE: Ansible
      DURATION: 10HRS
      TRAINER: Sivasaikumar
    ansible.builtin.debug:
      msg: " course is {{COURSE}}, duration is {{DURATION}}, Trainer is {{TRAINER}} "