- name: create a ec2 instance and route 53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-07bd49fd06e22e748
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-06cd04d955630159e
    instance_type: t3.micro
    zone: "jobsearchindia.online"
    names:
    - mysql
    - backend
    - frontend
  tasks:
  - name: Install python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      state: present
    loop:
    - botocore
    - boto3

  - name: create a 3ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
      security_group: "{{ sg_id }}"
    loop: "{{ names }}"
    register: "ec2_info"

  - name: print the ec2 instances output
    ansible.builtin.debug:
      msg : "{{ ec2_info }}"

  - name: print the private address
    ansible.builtin.debug:
      msg: "{{ item.instances[0].private_ip_address}}"
    loop: "{{ ec2_info.results }}"

  - name: create a private Route 53 records for all 3 instances
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{item.item}}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{ ec2_info.results }}"
    